name: 'Anchor Test 2024'
description: 'An "anchor test" action that runs in ~1 minute.'
branding:
  icon: anchor
  color: blue
inputs:
  node-version:
    description: 'Version of node.js to use'
    required: false
    default: '20.11.0' # LTS
  anchor-dir:
    description: 'anchor workspace directory'
    required: false
    default: '.' # LTS
  solana-cli-version:
    description: 'Version of Solana CLI to use'
    required: false
    default: '1.17.1' # stable
  anchor-version:
    description: 'Version of Anchor to use'
    required: false
    default: '0.29.0' # latest
  features:
    description: 'Features to pass to cargo'
    required: false
    default: 'default'
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3
    - name: Install Yarn
      run: npm install --global yarn
    - name: Install Solana
      uses: metaplex-foundation/actions/install-solana@v1
      with:
        version: ${{ inputs.solana-cli-version }}
    - uses: metadaoproject/setup-anchor@v2
      with:
        node-version: ${{ inputs.node-version }}
        solana-cli-version: ${{ inputs.solana-cli-version }}
        anchor-version: ${{ inputs.anchor-version }}
    - name: Cache node_modules
      uses: actions/cache@v3
      with:
        path: ./node_modules/
        key: node-modules-${{ runner.os }}-build-${{ inputs.node-version }}
    - name: Install node_modules
      run: yarn
      shell: bash
    - name: Create keypair
      run: solana-keygen new --no-bip39-passphrase --outfile ${{ inputs.anchor-dir }}/keypair.json
      shell: bash
    - name: Install Cargo toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        components: rustc
    - name: Cache Cargo dependencies
      uses: Swatinem/rust-cache@v2
    - name:  Start Local Validator
      run: solana-test-validator &
    - name: Run tests
      run: |
        cd ${{ inputs.anchor-dir }} ; anchor test --skip-local-validator -- --features ${{ inputs.features }}
      shell: bash

